feat(zshrc): `fzfcd`, 'rgcd', 'yzcd'

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -176,6 +176,92 @@ zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
 zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
 
 
+# FZF CONFIG
+
+# Source: https://github.com/junegunn/fzf/blob/master/ADVANCED.md
+fzfcd() { 
+  dir=$(fd --type file |
+    fzf --prompt 'Files> ' \
+    --header 'CTRL-T: Switch between Files/Directories' \
+    --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ Files ]] &&
+    echo "change-prompt(Files> )+reload(fd --type file)" ||
+    echo "change-prompt(Directories> )+reload(fd --type directory)"' \
+    --preview '[[ $FZF_PROMPT =~ Files ]] && bat --color=always {} || tree -C {}')
+  if [ -z "$dir" ]; then
+    echo "You didn't choose any file/directory"
+    exit 1
+  elif [ -d "$dir" ]; then
+    cd "$dir"
+  else
+    cd $(echo "$dir" | awk -F'/' 'OFS="/" {$NF=""; print}' | sed 's:/$::')
+  fi
+}
+
+bindkey -s '^f' 'fzfcd\n'
+
+rgcd() { 
+  rm -f /tmp/rg-fzf-{r,f}
+  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
+  INITIAL_QUERY="${*:-}"
+  dir=$(: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
+    --bind "start:reload:$RG_PREFIX {q}" \
+    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
+    --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] &&
+    echo "rebind(change)+change-prompt(1. ripgrep> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
+    echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
+    --color "hl:-1:underline,hl+:-1:underline:reverse" \
+    --prompt '1. ripgrep> ' \
+    --delimiter : \
+    --header 'CTRL-T: Switch between ripgrep/fzf' \
+    --preview 'bat --color=always {1} --highlight-line {2}' \
+    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
+  )
+  echo '[1] nvim'
+  echo '[2] cd'
+  read choice
+
+  case $choice in
+    1)
+      if [ -d "$dir" ]; then
+        echo "$dir is a directory, cannot open in nvim"
+        exit 1
+      else
+        nvim "$dir"
+      fi
+      ;;
+    2)
+      if [ -d "$dir" ]; then
+        cd "$dir"
+      else
+        cd $(echo "$dir" | awk -F'/' 'OFS="/" {$NF=""; print}' | sed 's:/$::')
+      fi
+      ;;
+    *)
+      echo "Invalid choice"
+      exit 1
+      ;;
+  esac
+}}
+
+bindkey -s '^g' 'rgcd\n'
+
+
+# YAZI CONFIG
+
+# ChatGPT gen it for me :(
+yzcd() {
+  local tmp=$(mktemp)
+  yazi "$@" --cwd-file="$tmp"
+  local cwd=$(<"$tmp")
+  if [[ -n "$cwd" && "$cwd" != "$PWD" ]]; then
+    cd "$cwd"
+  fi
+  rm "$tmp"
+}
+
+bindkey -s '^d' 'yzcd\n'
+
+
 # RUN SOME STUFF
 fastfetch
 eval "$(starship init zsh)"
